# Generated by Django 2.1.1 on 2020-03-14 12:05

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('spoiler', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anime.Anime')),
                ('dislike', models.ManyToManyField(blank=True, editable=False, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, editable=False, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='account.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'კომენტარი',
                'verbose_name_plural': 'კომენტარი',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='no-avatar.jpg', upload_to='avatars/', verbose_name='ავატარი')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'კაცი'), (1, 'ქალი')], null=True, verbose_name='სქესი')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'პროფილი',
                'verbose_name_plural': 'პროფილი',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_updated', models.DateTimeField(auto_now_add=True)),
                ('avatar_updated', models.DateTimeField(default=account.models.sub_three_days)),
                ('email_updated', models.BooleanField(default=False)),
                ('new_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'პარამეტრები',
                'verbose_name_plural': 'პარამეტრები',
            },
        ),
    ]
