# Generated by Django 2.1.1 on 2020-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email_updated',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='new_email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'მამრობითი'), (1, 'მდედრობითი')], null=True, verbose_name='სქესი'),
        ),
    ]
