# Generated by Django 2.1.1 on 2020-08-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200328_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='spoiler',
        ),
    ]
