# Generated by Django 2.1.1 on 2020-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='სახელი')),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField(verbose_name='წერილი')),
                ('date', models.DateField(auto_now_add=True, verbose_name='თარიღი')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('closed', models.BooleanField(default=False, verbose_name='დახურული')),
            ],
        ),
    ]
