# Generated by Django 2.1.1 on 2020-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
