# Generated by Django 2.1.1 on 2020-09-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='სახელი')),
                ('nameen', models.CharField(blank=True, max_length=100, verbose_name='ინგლისურად')),
                ('namejp', models.CharField(blank=True, max_length=100, verbose_name='იაპონურად')),
                ('nameru', models.CharField(blank=True, max_length=100, verbose_name='რუსულად')),
                ('poster', models.ImageField(blank=True, max_length=50, upload_to='posters/', verbose_name='სურათი')),
                ('year', models.PositiveSmallIntegerField(verbose_name='გამოშვების წელი')),
                ('director', models.CharField(max_length=40, verbose_name='რეჟისორი')),
                ('studio', models.CharField(max_length=20, verbose_name='სტუდია')),
                ('age', models.PositiveSmallIntegerField(verbose_name='შეზღუდვის ასაკი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'სერიალი'), (1, 'კინო')], default=0, verbose_name='ტიპი')),
                ('episodes', models.PositiveSmallIntegerField(default=1, verbose_name='ეპიზოდების რაოდენობა')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='რეიტინგი')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('dubbed', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='გახმოვანებული')),
                ('slug', models.SlugField(unique=True, verbose_name='ლინკი')),
                ('finished', models.BooleanField(default=False, verbose_name='დამთავრებულია')),
            ],
            options={
                'verbose_name': 'ანიმე',
                'verbose_name_plural': 'ანიმეები',
                'db_table': 'animes_list',
            },
        ),
        migrations.CreateModel(
            name='AnimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='ვიდეოს ლინკი')),
                ('row', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='მერამდენე ეპიზოდია')),
                ('anime', models.ForeignKey(limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='anime.Anime', verbose_name='ანიმე')),
            ],
            options={
                'verbose_name': 'ანიმე სერია',
                'verbose_name_plural': 'ანიმე სერიები',
                'db_table': 'animes_series',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Dubber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'გამხმოვანებელი',
                'verbose_name_plural': 'გამხმოვანებლები',
                'db_table': 'dubbers',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='anime.Category', verbose_name='ჟანრები'),
        ),
        migrations.AddField(
            model_name='anime',
            name='dubbers',
            field=models.ManyToManyField(related_name='dubbers', to='anime.Dubber', verbose_name='გამხმოვანებელი'),
        ),
    ]
