# Generated by Django 2.1.1 on 2020-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='nameen',
            field=models.CharField(blank=True, max_length=100, verbose_name='ინგლისურად'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='namejp',
            field=models.CharField(blank=True, max_length=100, verbose_name='იაპონურად'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='nameru',
            field=models.CharField(blank=True, max_length=100, verbose_name='რუსულად'),
        ),
    ]
