# Generated by Django 2.1.1 on 2020-03-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='anime',
            field=models.ForeignKey(limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='anime.Anime', verbose_name='ანიმე'),
        ),
    ]
