# Generated by Django 2.1.1 on 2020-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
