# Generated by Django 2.1.1 on 2020-02-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'კომენტარი', 'verbose_name_plural': 'კომენტარი'},
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='url',
            field=models.CharField(max_length=100, verbose_name='ვიდეოს ლინკი'),
        ),
    ]
