# Generated by Django 2.1.1 on 2020-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20200229_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='დისლაიქები'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='ლაიქები'),
        ),
    ]
