# Generated by Django 2.1.1 on 2020-03-01 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0003_auto_20200301_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, editable=False, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='დისლაიქები'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, editable=False, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='ლაიქები'),
        ),
    ]
