# Generated by Django 2.1.1 on 2020-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20200301_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
